#targets:
#  $default:
#    builders:
#      auto_route_generator|autoRouteGenerator:
#        enabled: true
#        generate_for:
#          include:
#            - lib/core/routes/app_router.dart
#          # [exclude] is not needed if at least one path is provided
#          # in [include]. It will only target [include]d paths
#          # exclude:
#          #   - ...
#
#      json_serializable:
#        enabled: true
#        generate_for:
#          exclude:
##            - lib/data/models/**/**.dart
#            - lib/data/models/auth/**.dart
#            - lib/data/models/qr_scan/**.dart
##            - lib/**_bloc.dart
##            - lib/**_cubit.dart
#
#        options:
#          explicit_to_json: true
#          include_if_null: false
#      freezed|freezed:
#        enabled: true
#        generate_for:
#          exclude:
##            - lib/data/models/**/**.dart
#            - lib/data/models/auth/**.dart
#            - lib/data/models/qr_scan/**.dart
##            - lib/**_bloc.dart
##            - lib/**_cubit.dart
#      hive_generator:
#        enabled: true
#        generate_for:
#          exclude:
#            - lib/data/models/auth/**.dart
#            - lib/data/models/qr_scan/**.dart