targets:
  $default:
    builders:
      # Typically the builder key is just the package name, run
      # `dart run build_runner doctor` to check your config.
      build_runner:build_runner:
        generate_for:
          # Example glob for only the Dart files under `lib/models`
#          - lib/data/models/**.bv.dart
          - test/data/datasources/local/auth_local_data_source_test.dart