const baseUrl = "dev-trackingbwa.my.id";
const apiUrl = "/api";
// const baseUrl = "zulfikar.bwa.id:88";
// const apiUrl = "/backend_inventory/api";
const loginUrl = "$apiUrl/login";
const scanUrl = "$apiUrl/scan_sj";
const storeUrl = "$scanUrl/store";
const historyUser = "$apiUrl/historyUser";
const historyAll = "$apiUrl/historyAll";
